version: "3.9"

services:
  registration:
    ports:
      - "8081:8081"
    build:
      context: .
    volumes:
      - ./cmd:/cmd
    depends_on:
      - sqlserver
  sqlserver:
    image: "postgres:14.1"
    ports:
      - "6080:5432"
    environment:
      POSTGRES_DB: models
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
#    command: "ll"


volumes:
  pg_data: