version: "3.9"

services:
  sqlserver:
    image: "postgres:14.1"
    ports:
      - "6080:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./scripts:/docker-entrypoint-tokensdb.d/
      - ./scripts:/docker-entrypoint-credentialsdb.d/
      - ./scripts:/docker-entrypoint-initdb.d/
      - pg_data:/var/lib/sql-server/data
  regir:
    ports:
      - "8081:8081"
    build:
      context: .


volumes:
  pg_data: